x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  image: settlement-system-airflow:2.9.3
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DEFAULT_TIMEZONE: utc
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    CLICKHOUSE_HOST: clickhouse
    CLICKHOUSE_PORT: 8123
    CLICKHOUSE_DATABASE: settlement_analytics
    CLICKHOUSE_USERNAME: hyuk
    CLICKHOUSE_PASSWORD: ${password}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins

services:
  airflow-postgres:
    image: postgres:15
    container_name: airflow-postgres
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    mem_limit: 768m
    mem_reservation: 512m
    depends_on:
      airflow-postgres:
        condition: service_healthy
    command: >
      bash -c "
      airflow db migrate &&
      (airflow users list | grep -q admin ||
      airflow users create
      --username admin
      --password admin
      --firstname Hyuk
      --lastname Admin
      --role Admin
      --email admin@example.com)
      "

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    mem_limit: 768m
    mem_reservation: 512m
    ports:
      - "8088:8080"
    command: webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    mem_limit: 768m
    mem_reservation: 512m
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  airflow-postgres-data:
