FROM gradle:8.5-jdk17 AS build
WORKDIR /app
COPY . .
RUN gradle :ad-streams:bootJar --no-daemon

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=build /app/ad-streams/build/libs/*.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "app.jar"]