FROM gradle:8.5-jdk17 AS build
WORKDIR /app
COPY . .
RUN gradle :api-server:bootJar --no-daemon

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=build /app/api-server/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]