server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/settlement-system
    username: hyuk
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-timeout: 1000
      validation-timeout: 500
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    streams:
      application-id: ad-click-streams
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      properties:
        num.stream.threads: 3
        auto.offset.reset: earliest
        state.dir: /tmp/kafka-streams/ad-click-streams
        commit.interval.ms: 1000
        processing.guarantee: exactly_once_v2
    clusters:
      primary:
        bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      dr:
        bootstrap-servers: localhost:49092,localhost:49093,localhost:49094

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true

app:
  kafka:
    budget-events-topic: budget-events
    remote-budget-events-topic: dr.budget-events
    budget-results-topic: budget-results
    remote-budget-results-topic: dr.budget-results
    budget_results_dlt: "budget-results.DLT"
    budget_results_dlt_group: "budget-result-dlt-group"