kafka.bootstrap.servers=localhost:19092,localhost:29092,localhost:39092

kafka.topic.budget-results=budget-results
kafka.topic.ad-impressions=ad-impressions
kafka.topic.ad-clicks=ad-clicks
kafka.topic.ad-conversions=ad-conversions
kafka.topic.user-segments=user-segments

kafka.group.budget-results=ad-analytics-budget-results-group
kafka.group.ad-impressions=ad-analytics-impressions-group
kafka.group.ad-clicks=ad-analytics-clicks-group
kafka.group.ad-conversions=ad-analytics-conversions-group
kafka.group.user-segments=ad-analytics-user-segments-group

clickhouse.url=jdbc:clickhouse://localhost:8123/settlement_analytics
clickhouse.username=hyuk
clickhouse.password=${password}
clickhouse.batch-size=500
clickhouse.batch-interval-ms=1000
clickhouse.max-retries=3

flink.parallelism=12
flink.checkpoint-interval-ms=10000
flink.checkpoint-timeout-ms=60000
flink.min-pause-between-checkpoints-ms=5000
flink.restart-attempts=3
flink.restart-delay-ms=5000
flink.network-memory-min=128mb
flink.network-memory-max=128mb

flink.watermark-out-of-orderness-seconds=5
flink.idle-timeout-seconds=10

flink.performance-emit-timeout-ms=70000

flink.tolerable-checkpoint-failure-number=3

kafka.topic.budget-results-parse-dlq=budget-results.parse-dlq
kafka.topic.ad-impressions-parse-dlq=ad-impressions.parse-dlq
kafka.topic.ad-clicks-parse-dlq=ad-clicks.parse-dlq
kafka.topic.ad-conversions-parse-dlq=ad-conversions.parse-dlq
kafka.topic.user-segments-parse-dlq=user-segments.parse-dlq
kafka.topic.unknown-segments-dlq=unknown-segments.dlq

flink.metric-window-minutes=1

flink.prometheus-metrics-port=9250
