server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/settlement-system
    username: hyuk
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6380

logging:
  level:
    com.hyuk.settlement: DEBUG