apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: ad-click-events
  namespace: kafka
  labels:
    strimzi.io/cluster: settlement-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    min.insync.replicas: "2"
    retention.ms: "604800000"
    cleanup.policy: delete