apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: settlement-kafka
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: settlement-kafka
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV0
    listeners:
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          bootstrap:
            loadBalancerIP: 127.0.0.1
          brokers:
            - broker: 0
              advertisedHost: 127.0.0.1
              advertisedPort: 31336
              loadBalancerIP: 127.0.0.1
            - broker: 1
              advertisedHost: 127.0.0.1
              advertisedPort: 30851
              loadBalancerIP: 127.0.0.1
            - broker: 2
              advertisedHost: 127.0.0.1
              advertisedPort: 30915
              loadBalancerIP: 127.0.0.1
  entityOperator:
    topicOperator: {}
    userOperator: {}