dependencies {
    implementation project(':shared')
    implementation project(':merchant')
    implementation project(':transaction')
    implementation project(':fee-policy')
    implementation project(':ledger')
    implementation project(':settlement')
    implementation project(':payout')
    implementation project(':advertiser')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    runtimeOnly 'com.h2database:h2'
}